### ISSUE TITLE
Support for host option

### ISSUE THREAD

**Issue by chrismcleod** [orta/vscode-react-native-storybooks#2]
May we have support for host option?  This helps when trying to run react native storybook on a real device.

https://github.com/storybooks/react-native-storybook/issues/122

**Comment by orta** [comment]
You're welcome to add it 👍

**Comment by chrismcleod** [comment]
Thank you sir here it is: https://github.com/orta/vscode-react-native-storybooks/pull/3

**Comment by chrismcleod** [comment]
Updated and works!  Thank you.
