### ISSUE TITLE
Prevent Previous/Next Story Keyboard Shortcuts from Conflicting with Cmd+K when Terminal is focused

### ISSUE THREAD

**Issue by kohlmannj** [orta/vscode-react-native-storybooks#22]
It appears that this extension prevents the default Command + K keyboard shortcut from working when the integrated Terminal is focused.

## Steps to Reproduce
1. Launch Visual Studio Code 1.14.2 on macOS Sierra 10.12.5 with the default keyboard shortcuts.
2. Use the Extensions sidebar to install the React Native Storybook extension and reload the Code window.
3. Open the integrated Terminal and focus it to begin entering text.
4. Run a command which produces output, such as `ls`.
5. With the Terminal still focused, attempt to clear it with the default Command + K keyboard shortcut.

## Expected Results
1. Code launches normally and opens a new window.
2. After the window reloads, the React Native Storybook extension is installed.
3. The Panel appears at the bottom of the code window with the integrated terminal active.
4. Running `ls` prints a list of folders in the current working directory of the terminal.
5. Typing Command + K clears the terminal, and the output of the previous command is no longer visible.

## Actual Results
1. Same
2. Same
3. Same
4. Same
5. The status bar at the bottom of the Code window displays the message, "(⌘K) was pressed. Waiting for second key of chord…". The output of the previous command is still visible in the terminal.

**Comment by orta** [comment]
Ah, probably needs to be scoped to editor active then

**Comment by orta** [comment]
Shipped a fix 👍 

Thanks for the comprehensive notes
