### ISSUE TITLE
Getting error when trying to reconnect

### ISSUE THREAD

**Issue by ghost** [orta/vscode-react-native-storybooks#25]
I am getting this error when trying to reconnect:

command 'extension.restartConnectionToStorybooks' not found

VSCode Version 1.16.0 (1.16.0)

**Comment by chris-mcleod** [comment]
In fact, seems to be an error for all storybook commands

**Comment by orta** [comment]
It's there in the code, https://github.com/orta/vscode-react-native-storybooks/blob/master/src/extension.ts#L143

I'd recommend maybe re-installing the extension

**Comment by chris-mcleod** [comment]
@orta i did try reinstalling it, this may have something to do with the fact i have multiple users on my mac and vscode doesnt seem to enjoy that.  Any ideas?

**Comment by orta** [comment]
Not that I can think of, would recommend cloning and running in dev mode to see if you can get some useful logs and debug it

**Comment by chris-mcleod** [comment]
ok im going to close this bc as you say, i dont think it is related to the newest vscode

**Comment by orta** [comment]
I tried a fresh install, and I'm getting this also 👍

**Comment by cem2ran** [comment]
This may have reappeared. A colleague and I are both getting it after Code update.
Currently running: 1.28.0 but may have appeared before this.

**Comment by gorhgorh** [comment]
same here ) 
react native project, init with the standard cli
```vscode : 1.28.1```
```vscode extension: 2.5.0```

```
storybook modules in the project: 
@storybook/react-native": "^4.0.0-alpha.25",
@storybook/addon-actions": "^4.0.0-alpha.25",
@storybook/addon-links": "^4.0.0-alpha.25",
@storybook/addons": "^4.0.0-alpha.25"
```

**Comment by orta** [comment]
I feel like this is when the extension hasn't loaded? I also saw it on last friday

**Comment by gorhgorh** [comment]
I tried to install / reinstall multiple time with the same effect, is there anything I can do to provide you with better information about the problem ?

**Comment by orta** [comment]
I'm getting this still - sigh

**Comment by orta** [comment]
I fixed this: https://github.com/orta/vscode-react-native-storybooks/commit/a33b87f7fe611324864dba874e17159193b1664c
