### ISSUE TITLE
cant find server at localhost:9001

### ISSUE THREAD

**Issue by ajonno** [orta/vscode-react-native-storybooks#5]
Just installed ```vscode-react-native-storybooks``` in VS Code 1.12.2 ; have a 0.44 React Native app open etc.

After selecting Show Storybooks I see this error. How/where can I set the correct port# ?

![image](https://cloud.githubusercontent.com/assets/3005269/26611371/432f34de-45f1-11e7-8d4e-16cea69604c6.png)

**Comment by orta** [comment]
There are settings in the extension for the port, check out the README 👍
